services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /home/mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  plugins-api:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-plugins-api.git
      args:
        - OTEL_OPTS=
    image: plugins-api
    restart: always
    ports:
      - "8083:8083"
      - "8003:8003"
    environment:
      - server.port=8083
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - server.servlet.context-path=/remote-falcon-plugins-api
      - sequence-limit=200
    depends_on:
      - mongo
  control-panel:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-control-panel.git
      args:
        - OTEL_OPTS=
    image: control-panel
    restart: always
    ports:
      - "8081:8081"
      - "8001:8001"
    environment:
      - server.port=8081
      - web.url=https://your_domain.com #Change "your_domain" to your real domain
      - auto-validate-email=true
      - jwt.user=123456 #Change this to a random value
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - github.pat=
      - sendgrid.key=
      - client.header=CF-Connecting-IP
      - s3.endpoint=dummy
      - s3.accessKey=dummy
      - s3.secretKey=dummy
    depends_on:
      - mongo
  viewer:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-viewer.git
      args:
        - OTEL_URI=
        - MONGO_URI=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
    image: viewer
    restart: always
    ports:
      - "8082:8082"
      - "8002:8002"
    environment:
      - quarkus.http.port=8082
      - client.header=CF-Connecting-IP
    depends_on:
      - mongo
  ui:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-ui.git
      args:
        - HOST_ENV=prod
        - VERSION=1.0.0
        - CONTROL_PANEL_API=https://your_domain.com/remote-falcon-control-panel #Change "your_domain" to your real domain
        - VIEWER_API=https://your_domain.com/remote-falcon-viewer #Change "your_domain" to your real domain
        - GOOGLE_MAPS_KEY=
        - PUBLIC_POSTHOG_KEY=
        - GA_TRACKING_ID=1
        - HOSTNAME_PARTS=2 #Change this to the number of parts in your hostname. For example, domain.com would be two parts ('domain' and 'com'), and sub.domain.com would be 3 parts ('sub', 'domain', and 'com')
        - SOCIAL_META=<meta property='og:url' content='https://remotefalcon.com/'/><meta property='og:title' content='Remote Falcon'/><meta property='og:description' content='Create a custom website where viewers can request or vote for sequences to watch on your light show.'/><meta property='og:image' content='https://remotefalcon.com/jukebox.png'/>
        - SWAP_CP=false
        - VIEWER_PAGE_SUBDOMAIN= #Set this to your show subdomain (show name in all lowercase with no spaces) if you have set SWAP_CP to true
    image: ui
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - control-panel
      - viewer
