services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /some/local/path/mongo-volume:/data/db #Update the path before the : to a valid path on your machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  plugins-api:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-plugins-api.git
      args:
        - OTEL_OPTS=
    restart: always
    ports:
      - "8083:8083"
      - "8003:8003"
    environment:
      - server.port=8083
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - server.servlet.context-path=/remote-falcon-plugins-api
      - sequence-limit=200
    depends_on:
      - mongo
  control-panel:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-control-panel.git
      args:
        - OTEL_OPTS=
    restart: always
    ports:
      - "8081:8081"
      - "8001:8001"
    environment:
      - server.port=8081
      - web.url=http://localhost:3000
      - auto-validate-email=true
      - jwt.user=123456
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - github.pat=
      - sendgrid.key=
      - client.header=CF-Connecting-IP
      - s3.endpoint=dummy
      - s3.accessKey=dummy
      - s3.secretKey=dummy
    depends_on:
      - mongo
  viewer:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-viewer.git
      args:
        - OTEL_URI=
        - MONGO_URI=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
    restart: always
    ports:
      - "8082:8082"
      - "8002:8002"
    environment:
      - quarkus.http.port=8082
      - client.header=CF-Connecting-IP
    depends_on:
      - mongo
  ui:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-ui.git
      args:
        - HOST_ENV=local
        - VERSION=local
        - CONTROL_PANEL_API=http://localhost:8081/remote-falcon-control-panel
        - VIEWER_API=http://localhost:8082/remote-falcon-viewer
        - GOOGLE_MAPS_KEY=
        - PUBLIC_POSTHOG_KEY=
        - GA_TRACKING_ID=1
        - HOSTNAME_PARTS=1
        - SOCIAL_META=
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - control-panel
      - viewer
